name: Docker Build and Push

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Copy .env.local
      run: cp .env.local ./.env.local
      
    - name: Build and push Docker image
      run: |
        docker build -t pamelamarku/mongodb-mongoose-test .
        docker push pamelamarku/mongodb-mongoose-test
